#	GPL-3.0-only or GPL-3.0-or-later
#	«Copyright 2019 Instituto Geografico Nacional»
#	This file is part of caster REP.
#	Caster REP is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#	Caster REP is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#	You should have received a copy of the GNU General Public License
#	along with Foobar.  If not, see <http://www.gnu.org/licenses/>.

#	Contact: <jdcenteno@fomento.es>


#    ___________________________________________________________
#     __   __        ___    __        __      __ __     __
#    /  ` /  \ |\ | |__  | / _` |  | |__)  /\   |    | /  \ |\ |
#    \__, \__/ | \| |    | \__| \__/ |  \ /~~\  |    | \__/ | \|
#    ___________________________________________________________

#    Here we can define some general constants for the scripts.
 
#    -------------
#    SETTINGS
#    -------------
[SETTINGS]
# --  ENVIRONMENT  -- #
[[ENVIRONMENT]]
#Python version used to launch subprocesses
STR_PYTHON_VERSION = 'python'
#Directory used to store ouput data
DIR_OUTPUT = 'DATA'

# -- CORE FILES -- #
[[CORE FILES]]
FILE_MONGODB_CREATE_USER = 'MongoDB_Create_USER.py'
FILE_MONGODB_INIT = 'REP_init_mongodb.py'
#NTRIP Client file name
FILE_NTRIP_CLIENT = 'NTRIP_CLIENT_IGN_ESP_6p3.py'
#CASTER Server file name
FILE_NTRIP_CASTER = 'REP_caster_server.py'
#DECODER class
FILE_RTCM3_DECODE = 'RTCM3_Decode6.py'

# -- MongoDB Config -- #
[[MONGODB]]
DIR_BACKUP = '/var/backups/mongo/' #for linux
#DIR_BACKUP = 'c:/data/backups/mongo/' #for windows all path
#DIR_TEMP_RESTORE = 'c:/tmp/mongo_dump/' #for windows all path
DIR_TEMP_RESTORE = '/tmp/mongo_dump/'
# for windows all path  # '/tmp/mongo_dump/'
HOST_MONGODB = '127.0.0.1'
PORT_MONGODB = 27017

# --  PREFERENCES  -- #
[[PREFERENCES]]
# Time to consider if an station is not sending new packets with raw data (max. latency)
TIME_OUT_RAWDATA = 30
# Define how you named your nearest solution in your streams database
STR_NEAREST_MOUNPOINT = 'NEAREST'
# Time to refresh control panel
# Messages window
TIME_REFRESH_MSG = 1000
# Status frame
TIME_REFRESH_STATUS = 15000
# Time to wait between comands to be executed
TIME_EXECUTION_DELAY = 5



#    -------------
#    PROFILE
#   -------------
[PROFILE]
# -- I / O -- #
[[IO]]
# RTCM3 Capture Script config  
# Host where a server will listen RTCM packets RTCM from a NTRIP Server 1.0
RTCM_CAPTURE_SERVER_HOST = '0.0.0.0'
# Port where a server will listen RTCM packets RTCM from a NTRIP Server 1.0
RTCM_CAPTURE_SERVER_PORT = 2103
# Caster Client Server (Main Server) 
# Main Server, where clients will request for mountpoints rtcm data
CASTER_SERVER_HOST = '0.0.0.0'
# Main server port 
CASTER_SERVER_PORT = 2101

# -- DATABASE -- #
[[DATABASE]]
STR_MONGODB_AUTH_USER = 'c_rep'
STR_MONGODB_AUTH_PASSWD = '1qazxsw2'
# DataBase Name with collections
str_db_Name = 'casterrep'
# 'users' collection (table)
str_db_UsersTable = 'users'
# 'rtcm_raw' collection (table)
str_db_RTCMTable = 'rtcm_raw'
# 'streams' collection (table) 
str_db_StreamsTable = 'streams'
# 'comms' (host & port, user & password) collection (table) for each mountpoint
str_db_CommTable = 'comms'
# 'rover_connections' collection (table) 
str_db_RoverConnections = 'rover_connections'
