# -*- coding: UTF-8 -*-
NEAREST_MOUNPOINT = "NEAREST"

RTCM_CAPTURE_SERVER_HOST = "0.0.0.0"
RTCM_CAPTURE_SERVER_PORT = 2103

CASTER_SERVER_HOST = "0.0.0.0"
CASTER_SERVER_PORT = 2101

MONGODB_HOST_PORT = '127.0.0.1:27017'
MONGODB_AUTH_USER = 'CHANGE_ME'
MONGODB_AUTH_PASSWD = 'CHANGE_ME'

RAWDATA_TIMEOUT = 30
